#spring:
#  datasource:
#    url: jdbc:postgresql://ec2-54-89-105-122.compute-1.amazonaws.com:5432/d646o56khrmqpp
#    username: xoxfhafbxbtypx
#    password: 6d01b48d2a1df458612be2266afb54905952862eeaecbcc15ba5b28ca31d10c0
#    type: com.zaxxer.hikari.HikariDataSource
#    driver-class-name: org.postgresql.Driver
#    hikari:
#      pool-name: HrPortalHikariPool
#      auto-commit: false
#      connection-timeout: 10000
#      idle-timeout: 60000
#      max-lifetime: 120000
#      minimum-idle: 5
#      maximum-pool-size: 10
#  jpa:
#    database: postgresql
#    show-sql: false
#    hibernate:
#      ddl-auto: update
#      naming:
#        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
#    properties:
#      hibernate:
#        format_sql: true
#    open-in-view: false
#  servlet:
#    multipart:
#      max-file-size: 3MB